version: "3.7"
services:
  traefik:
    image: "traefik"
    restart: always
    command:
      - "--api=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      - "--certificatesresolvers.mytlschallenge.acme.email=${SSL_EMAIL}"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Added for the Traefik dashboard
    volumes:
      - traefik_data:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - web

  landing:
    build:
      context: ./landing
      dockerfile: Dockerfile
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.landing.rule=Host(`${DOMAIN_NAME}`) || Host(`www.${DOMAIN_NAME}`)
      - traefik.http.routers.landing.tls=true
      - traefik.http.routers.landing.entrypoints=web,websecure
      - traefik.http.routers.landing.tls.certresolver=mytlschallenge
      - traefik.http.services.landing.loadbalancer.server.port=3000
      - traefik.http.middlewares.landing-headers.headers.SSLRedirect=true
      - traefik.http.middlewares.landing-headers.headers.STSSeconds=315360000
      - traefik.http.middlewares.landing-headers.headers.browserXSSFilter=true
      - traefik.http.middlewares.landing-headers.headers.contentTypeNosniff=true
      - traefik.http.middlewares.landing-headers.headers.forceSTSHeader=true
      - traefik.http.middlewares.landing-headers.headers.SSLHost=${DOMAIN_NAME}
      - traefik.http.middlewares.landing-headers.headers.STSIncludeSubdomains=true
      - traefik.http.middlewares.landing-headers.headers.STSPreload=true
      - traefik.http.routers.landing.middlewares=landing-headers@docker
    environment:
      - NODE_ENV=production
    networks:
      - web

  crewai:
    build:
      context: ./crew
      dockerfile: Dockerfile
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.crewai.rule=Host(`crew.${DOMAIN_NAME}`)
      - traefik.http.routers.crewai.tls=true
      - traefik.http.routers.crewai.entrypoints=web,websecure
      - traefik.http.routers.crewai.tls.certresolver=mytlschallenge
      - traefik.http.services.crewai.loadbalancer.server.port=5000
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    volumes:
      - crewai_data:/app/data
    networks:
      - web

volumes:
  traefik_data:
    external: true
  crewai_data:

networks:
  web:
    driver: bridge