research_task:
  description: >
    Effectuez des recherches approfondies sur {topic} pour le contenu du podcast.
    Identifiez les sous-sujets tendance, les perspectives clés et les angles narratifs potentiels.
    Assurez-vous que les informations sont à jour en {current_year}.
    Utilisez le WebSearchTool pour trouver des informations actuelles.
    Tous les résultats doivent être en français avec un style québécois.
  expected_output: >
    Un rapport de recherche complet sous forme d'objet JSON avec:
    {
      "sujet": "Sujet principal",
      "sous_sujets": ["Sous-sujet 1", "Sous-sujet 2", ...],
      "sources": [
        {"titre": "Titre de la source", "url": "URL de la source", "perspectives": "Perspectives clés de cette source"}
      ],
      "angles": ["Angle narratif 1", "Angle narratif 2", ...]
    }
  agent: researcher

topic_curation_task:
  description: >
    Examinez les résultats de recherche et sélectionnez les sujets les plus captivants.
    Choisissez des sous-sujets qui créeront le récit de podcast le plus engageant.
    Assurez-vous que tout est en français québécois.
  expected_output: >
    Une sélection de sujet affinée sous forme d'objet JSON avec:
    {
      "sujet_principal": "Le sujet principal affiné",
      "justification": "Explication de pourquoi c'est captivant",
      "points_clés": ["Point 1", "Point 2", ...],
      "questions": ["Question 1", "Question 2", ...],
      "public_cible": "Description du public idéal"
    }
  agent: topic_curator

script_writing_task:
  description: >
    Développez un script complet de podcast basé sur les sujets sélectionnés.
    Créez un récit conversationnel et engageant qui s'écoule naturellement.
    Incluez des introductions, des segments de contenu principal et des remarques finales.
    Le script DOIT être entièrement en français québécois avec des expressions locales.
    Créez un dialogue entre Alex et Simon uniquement.
  expected_output: >
    Un script complet de podcast formaté pour la production audio, comprenant:
    - Segments d'intro et d'outro
    - Contenu principal divisé en segments clairs
    - Dialogue naturel et flux conversationnel entre Alex et Simon
    - Durée totale estimée
    - Expressions québécoises authentiques
  agent: script_writer

audio_production_task:
  description: >
    Fournissez des directives complètes de production audio pour le script du podcast.
    Précisez les caractéristiques vocales recommandées, le rythme et le formatage audio.
    Utilisez l'ElevenLabsTool pour convertir du texte d'exemple en audio si nécessaire.
    Assurez-vous que les voix sont configurées pour le français québécois.
    Utilisez uniquement les voix Alex et Simon.
  expected_output: >
    Directives détaillées de production audio sous forme d'objet JSON avec:
    {
      "profils_voix": {
        "Alex": {"voice_id": "alex", "caracteristiques": "Description des qualités vocales"},
        "Simon": {"voice_id": "simon", "caracteristiques": "Description des qualités vocales"}
      },
      "rythme": "Description du rythme tout au long du podcast",
      "ton": "Recommandations générales de ton",
      "specs_audio": {
        "format": "mp3",
        "bitrate": "192kbps",
        "traitement": "Traitement audio recommandé"
      },
      "musique": {
        "intro": "Description de la musique",
        "outro": "Description de la musique",
        "transitions": "Description des sons de transition"
      },
      "notes_production": "Considérations supplémentaires de production",
      "accentuation_quebecoise": "Conseils pour renforcer l'accent québécois"
    }
  agent: audio_director